In [80]:
import numpy as np
a=np.random.random((10, 3))
i = np.arange(10)
print (a)
print (a[i,np.argmin (abs((a[0]-0.5)))])

[[0.70702203 0.3208917  0.06518332]
 [0.05142874 0.56299347 0.05621469]
 [0.34003111 0.27403232 0.4581255 ]
 [0.02399495 0.47881808 0.99837134]
 [0.22182669 0.85859682 0.95868724]
 [0.73939161 0.28527499 0.23135176]
 [0.39111366 0.25954757 0.59777316]
 [0.88762722 0.37453228 0.49902016]
 [0.48186982 0.2884296  0.7971769 ]
 [0.08437502 0.41071797 0.72960436]]
[0.3208917  0.56299347 0.27403232 0.47881808 0.85859682 0.28527499
 0.25954757 0.37453228 0.2884296  0.41071797]


In [103]:
import numpy as np
a=np.random.random((6, 6))                           
i = np.arange(6)
print(a)
print(a.sum(axis=1)/a.min(axis=0))

[[0.69936793 0.90377875 0.22451304 0.77463807 0.52734177 0.1347313 ]
 [0.31260548 0.39185701 0.29914536 0.02275343 0.1599467  0.07233269]
 [0.90969027 0.06654996 0.43338674 0.87453693 0.10681436 0.11393491]
 [0.60305652 0.20523122 0.11965945 0.32600316 0.08424025 0.78536997]
 [0.23418731 0.94342055 0.34176433 0.88876279 0.03699291 0.41157253]
 [0.74033878 0.44019808 0.14638308 0.62047486 0.58233867 0.20396322]]
[13.93914474 18.91271901 20.93368434 93.32926072 77.22290931 37.79337792]


In [9]:
import numpy as np
x = np.array([6,2,0,3,0,0,6,7,0,10])
print(max(np.array([x[i] for i in range(1,9) if x[i-1] == 0])))

6


In [87]:
a = np.ones(10)
i = np.array([0, 1, 2, 3, 5, 5, 5, 8])
a += np.bincount(i, minlength=len(a))
print(a)

[2. 2. 2. 2. 1. 4. 1. 1. 2. 1.]


In [12]:
import numpy as np
a = np.arange(16).reshape(4,4)
print(a)
a = np.arange(16).reshape(4, 4)
print(a)
print(a.diagonal(-1))
print({3-i:a.diagonal(3-i).tolist for i in range (7)})

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[ 4  9 14]
{3: <built-in method tolist of numpy.ndarray object at 0x0000025720874440>, 2: <built-in method tolist of numpy.ndarray object at 0x0000025720A5B710>, 1: <built-in method tolist of numpy.ndarray object at 0x0000025720A5B850>, 0: <built-in method tolist of numpy.ndarray object at 0x0000025720A5B8A0>, -1: <built-in method tolist of numpy.ndarray object at 0x0000025720A5B8F0>, -2: <built-in method tolist of numpy.ndarray object at 0x0000025720A5B940>, -3: <built-in method tolist of numpy.ndarray object at 0x0000025720A5B990>}


In [8]:
import numpy as np
import matplotlib.pyplot as plt
def _kmeans(data, k):
    centers = np.random.rand(k,2)
    _y =[]
    while True:
        dist = np.array([[np.linalg.norm(data[i]-centers[j]) for j in range(k)] for i in range(data.shape[0])])
        y = np.array([dist[i].argmin() for i in range(data.shape[0])]).reshape(data.shape[0],1)
        if (np.array_equal(y,_y)):
            break
        _y=y
        a_x = np.array([np.mean([data[i][0] for i in range(data.shape[0]) if y[i]==j] + [centers[j][0]]) for j in range(k)]).reshape(k,1)
        a_y = np.array([np.mean([data[i][1] for i in range(data.shape[0]) if y[i]==j] + [centers[j][1]]) for j in range(k)]).reshape(k,1)
        centers = np.array([[a_x[i], a_y[i]] for i in range(k)]).reshape(k,2)
    d = 0
    for i in range(k):
        for j in range(data.shape[0]):
            if y[j] == i:
                d += np.linalg.norm(centers[i] - data[j])*np.linalg.norm(centers[i] - data[j])
    return [d, y]
n = int(input("Input number of points: "))
k = 15
data = np.random.rand(n,2)
[d, y] = _kmeans(data, k)
print("Deviation : ",d)
plt.scatter(*data.T, c = y[:,0], s = 15)
plt.show()

Input number of points: 5
Deviation :  0.01980330726243669


<Figure size 640x480 with 1 Axes>